=-*- mode: org; mode: visual-line;  -*-=
#+STARTUP: indent

* =tramway=
** Changelog
- =1.0.0=, =2014-11-27= :: Yet another project rename (=tramway=).
- =0.8.0-SNAPSHOT=, =2014-10-31= :: Breaking change: =click?= for mouse-down is now =click-type=, values =:down= and =:up=. Note: no tracking of clicked object (a la SHADO) yet.
- =0.7.0-SNAPSHOT=, =2014-10-30= :: Breaking change: =auto/empty= -> =auto/void=.
- =0.6.0-SNAPSHOT=, =2014-10-15= :: Breaking change: start of conversion to protocols for nodes. Initial mouse tracking. `rect` and `disc` now take a `=z=`, as well as optional mouse callback function(s).

- =0.5.0-SNAPSHOT=, =2014-10-15= :: Breaking change: =start= takes optional renderer as argument, default is =:java2d= (as in Quil) rather than =:p3d=.

- =0.4.0-SNAPSHOT=, =2014-10-10= :: Breaking changes: =update= now takes a =time= argument (first); form initialisation routine is now called =init-form-state= (not =init-struct-state=).

- =0.3.0-SNAPSHOT=, =2014-10-09= :: Breaking change: form =update= is expected to return a map with =:form-state= and =:auto-state= (so that the =update= call can also modify the global automation state). Automation state changes cascade through the forms. Camera position and background colour are applied after all forms have been evaluated.

- =0.2.0-SNAPSHOT=, =2014-10-04= :: Breaking change: =auto-gate= takes =:in= param instead of =:at=.

- =0.1.0-SNAPSHOT=, =2014-09-21= :: Initial check-in (from previous =calamus= project, Berlin CCL).

** License

Copyright © 2014 Nick Rothwell.

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
